FROM dmascot/asdf:latest

SHELL ["/bin/bash","-c"]

RUN apk add --no-cache build-base zlib-dev libffi-dev \
    openssl-dev readline-dev xz-dev sqlite-dev sqlite-libs \
    curl bzip2-dev coreutils bash-completion